config/routes.rb
Rails.application.routes.draw do
  root to: 'books#eager_loading' # /
  get '/lazy_loading', to: 'books#lazy_loading', as: :lazy_loading
  get '/eager_loading', to: 'books#eager_loading', as: :eager_loading
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :publishers, dependent: :destroy

  validates :name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  validates :title, presence: true
  validates :title, uniqueness: { scope: :author }
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action do
        Rack::MiniProfiler.authorize_request
        Rack::MiniProfiler.config.position = 'top-left'
        Rack::MiniProfiler.config.show_total_sql_count = true
        Rack::MiniProfiler.config.skip_paths = ['/favicon.ico']
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.includes(:author)
    # @books = Book.all
  end

  def eager_loading
    @version = 'Eager Loading (No N+1 problem present)'
    @code = "@books = Book.includes(author: [:publishers]) # publishers belongs to authors; we are including two extra tables."

    @books = Book.includes(author: [:publishers])

    render :index
  end

  def lazy_loading
    @version = 'Lazy Loading (N+1 problem present)'
    @code = "@books = Book.all # We do not include authors or publishers; instead, in the view we iterate through all 500 books and make 500+ more queries to authors and publishers." 

    @books = Book.all

    render :index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<div class="container">
  <br>
  <h2><%= @version %></h2>
  <p>Click on the Rack Mini Profiler in the top-left of the screen to see the loading time!</p>
  <hr>
  <code>
    # app/controllers/books_controller.rb<br>
    def index<br>
    &nbsp&nbsp<%= @code %><br>
    end
  </code>
  <hr>
  <ol>
    <% @books.each do |book| %>
      <li>
        <strong><%= book.title %></strong> by <%= book.author.name %> 
        <strong>Published by:</strong><em><%= book.author.publishers.map { |publisher| publisher.content }.join(';') %></em>
        <hr/>
      </li>
    <% end %>
  </ol>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render '/partials/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link"  href="<%= eager_loading_path %>">Eager Loading</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= lazy_loading_path %>">Lazy Loading</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        </div>
      </li>
    </ul>
  </div>
</div>